### ISSUE TITLE
Do not send empty subtitles

### ISSUE THREAD

**Issue by harti2006** [zalando-stups/mint-worker#11]
The request to the service user api for creating / updating users, must not contain an empty string `""` in the `subtitle` property

**Comment by prayerslayer** [comment]
I find this stupid. Couldn't they check this on their side? I mean, it's perfectly valid to have an empty string as subtitle.

**Comment by hjacobs** [comment]
:+1: the service API should accept empty subtitles (why not?)

**Comment by prayerslayer** [comment]
Closing because of presumed irrelevancy.
