### ISSUE TITLE
Consider deletion of inactive applications

### ISSUE THREAD

**Issue by prayerslayer** [zalando-stups/mint-worker#15]
Applications that were never synced, but are inactive, live forever in mint-storage and that hurts our monitoring currently, because we cannot distinguish them from apps actually waiting for syncs.

**Comment by hjacobs** [comment]
:+1: we should do this "soonish" to improve our monitoring

**Comment by prayerslayer** [comment]
One disadvantage: You lose your service user configuration (mint bucket...) after inactivation and have to re-enter it if you decide to activate the application again.
