### ISSUE TITLE
Don't request Password Creation if Credential Storage cannot be contacted

### ISSUE THREAD

**Issue by ZroMnc** [zalando-stups/mint-worker#7]
In order to have a clean process on password creation please consider the following:

_As:_ Mint consumer
_I want:_ that requests for credential creation are only send when a storage container is specified
_So that:_ passwords are not created for a user and stored in their profile

Thanks
/Chris

**Comment by ZroMnc** [comment]
Sorry just saw already in -  Must not attempt to set credentials if no S3 bucket is configured #5

**Comment by hjacobs** [comment]
Yes, duplicate of #5
